In [1]:
#Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [9]:
import numpy as np
original_list1 = [12.23, 13.32, 100, 36.32]
myarray1 = np. array (original_list1)
print (myarray1)
print (original_list1)

[ 12.23  13.32 100.    36.32]
[12.23, 13.32, 100, 36.32]


In [16]:
q2 = [[2,3,4],[5,6,7],[8,9,10]]
myarray2 = np. array (q2)
print (myarray2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [23]:
myarray3 = np.zeros(10)
print (myarray3) 
myarray3 [6]= 11
print (myarray3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [26]:
myarray4 = np.arange(12,20)
print (myarray4) 

[12 13 14 15 16 17 18 19]


In [29]:
myarray5 = np.arange(12,21)
myarray5_ = myarray5 [::-1]

print (myarray5_)

[20 19 18 17 16 15 14 13 12]


In [32]:
myarray6 = np.arange(1,5)
myarray6_ = np.asfarray (myarray6)
print (myarray6_)

[1. 2. 3. 4.]


In [56]:
q7 = np.ones((5, 5))
print (q7)
q7 [1:-1, 1:-1]= 0

print (q7)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [61]:
q8 = np.ones((3, 3))
print (q8)

q8_ = np.pad (q8, pad_width=1, mode='constant', constant_values=0)
print (q8_)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [83]:
q9 = np.zeros((8, 8))
print (q9)
q9 [1::2, ::2]= 1
q9 [::2, 1::2]= 1
print (q9)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [92]:
q10 = ([8, 4, 6], [1, 2,3])
print (q10)
q10_ = np.asarray(q10)
print (q10_)

([8, 4, 6], [1, 2, 3])
[[8 4 6]
 [1 2 3]]


In [96]:
q11 = [10,20,30]
q11_= np.append (q11, [[40,50,60],[70,80,90]])
print (q11_)

[10 20 30 40 50 60 70 80 90]


In [7]:
import numpy as np
Cen = [-17.77777778, -11.11111111, 7.33888889, 1.11111111, 37.72777778]

q12_C = np.array(Cen)

print(q12_C)
print(np.round((9*q12_C/5 + 32),2)) #virgülden sonra 2 hane

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]
[-0.   12.   45.21 34.   99.91]


In [9]:
q13 = np.array([1,2,3], dtype=np.float64)
print("Size: ", q13.size)
print("Length: ", q13.itemsize)
print("Total bytes: ", q13.nbytes)

Size:  3
Length:  8
Total bytes:  24


In [11]:
q14_1 = np.array([0, 10, 20, 40, 60])
print(q14_1)
q14_2 = np.array ([10, 30, 40])
print(q14_2)

print(np.intersect1d(q14_1, q14_2)) #iki dizideki ortak elemanlar

[ 0 10 20 40 60]
[10 30 40]
[10 40]


In [12]:
q15 = np.array([10, 10, 20, 20, 30, 30])

print(q15)

print(np.unique(q15))

[10 10 20 20 30 30]
[10 20 30]


In [17]:
q16_1 = np.array([0, 10, 20, 40, 60, 80])
print(q16_1)
q16_2 = np.array([10, 30, 40, 50, 70])
print(q16_2)

print(np.setdiff1d(q16_1, q16_2)) #1 de olup 2 de olmayan
print(np.setdiff1d(q16_2, q16_1)) #2 de olup 1 de olmayan

[ 0 10 20 40 60 80]
[10 30 40 50 70]
[ 0 20 60 80]
[30 50 70]


In [18]:
q17_1 = np.array([0, 10, 20, 40, 60, 80])
print(q17_1)
q17_2 = np.array([10, 30, 40, 50, 70])
print(q17_2)

print(np.setxor1d(q17_1, q17_2)) #iki dizide farklı olanları yaz


[ 0 10 20 40 60 80]
[10 30 40 50 70]
[ 0 20 30 50 60 70 80]


In [23]:
q18_1 = np.array([ 0, 10, 20, 40, 60, 80])
print(q18_1)
q18_2 = np.array([10, 30, 40, 50, 70])
print(q18_2)

print(np.union1d(q18_1, q18_2))


[ 0 10 20 40 60 80]
[10 30 40 50 70]
[ 0 10 20 30 40 50 60 70 80]


In [24]:
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))


False
True
False
True


In [25]:
q20 = np.array([1, 2, 3, 4, 5, 6])
print (q20)
print(np.argmax(q20)) #maximum değerin index karşılığı
print(np.argmin(q20)) #min değerin index karşılığı


[1 2 3 4 5 6]
5
0


In [27]:
q21 = np.array([[0, 10, 20], [20, 30, 40]])

print(q21)
print(q21[q21>10]) #10 dan büyük değerler
print(np.nonzero(q21 > 10)) #10 dan büyük değerlerin index


[[ 0 10 20]
 [20 30 40]]
[20 20 30 40]
(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [28]:
q23 = np.array([[10, 20, 30], [20, 40, 50]])

print(q23)
q23_2 = np.ravel(q23)

print(q23_2)

[[10 20 30]
 [20 40 50]]
[10 20 30 20 40 50]


In [30]:
q24_1 = np.array([1, 2, 3, 4, 5, 6])
q24_2 = np.reshape(q24_1,(3,2))

print(q24_2)

q24_3 = np.reshape(q24_1,(2,3))

print(q24_3)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [33]:
q25 = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(q25)
print(q25.dtype)

q25_1= q25.astype(float)
print(q25_1.dtype)
print(q25_1)

[[ 2  4  6]
 [ 6  8 10]]
int32
float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


In [35]:
q26 =  np.logspace(2., 5., 20, endpoint=False)
print(q26)

[  100.           141.25375446   199.5262315    281.83829313
   398.10717055   562.34132519   794.32823472  1122.0184543
  1584.89319246  2238.72113857  3162.27766017  4466.83592151
  6309.5734448   8912.50938134 12589.25411794 17782.79410039
 25118.8643151  35481.33892336 50118.72336273 70794.57843841]


In [38]:
q27_1 = np.array([[0, 1, 3], [5, 7, 9]])
q27_2 = np.array([[0, 2, 4], [6, 8, 10]])
q27_12 = np.concatenate((q27_1, q27_2), 1)
print(q27_12)


[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [41]:
q28_1 = np.arange(1, 15)
print(q28_1)

print(np.split(q28_1, [2, 6]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


In [42]:
q29 = np.arange(16).reshape((4, 4))
print(q29)

print(np.hsplit(q29, [2, 6]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


In [43]:
q30 = np.array([[0, 10, 20], [20, 30, 40]])

print(q30)

print(np.count_nonzero(q30))

[[ 0 10 20]
 [20 30 40]]
5


In [45]:
q31_1 = np.array([[10,20,30], [40,50,60]])
q31_2 = np.array([[100], [200]])
print(np.append(q31_1, q31_2, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [47]:
q32 = np.array([-1, -4, 0, 2, 3, 4, 5, -6])

print(q32)

q32[q32 < 0] = 0
print(q32)


[-1 -4  0  2  3  4  5 -6]
[0 0 0 2 3 4 5 0]


In [48]:
q34_1 = np.array([97, 101, 105, 111, 117])
q34_2 = np.array(['a','e','i','o','u'])

print(q34_1)
print(q34_2)

print(q34_2[(100 < q34_1) & (q34_1 < 110)])

[ 97 101 105 111 117]
['a' 'e' 'i' 'o' 'u']
['e' 'i']


In [50]:
q36 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(q36)
q36_1 = q36[:,[1,2]]

print(q36_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
